import React, { createContext, useState, useContext, useEffect } from 'react';

const LanguageContext = createContext();

const translations = {
  en: {
    // Landing Page
    miniCup: 'Mini Cup',
    clubWorldCup: 'Who is the greatest?',
    tagline: 'Help your team win',
    startPlaying: 'Start Playing',
    stats: 'Stats',
    comingSoon: 'Coming Soon',
    adminPanel: 'Admin Panel',
    teamsCompeting: 'Teams Competing',
    totalGoals: 'Total Goals Scored',
    playersWorldwide: 'Players Worldwide',
    howToPlay: 'How to Play',
    step1Title: '1. Choose Your Team',
    step1Desc: 'Select your country, then pick your favorite team',
    step2Title: '2. Aim & Kick',
    step2Desc: 'Choose where to shoot inside the goal, then tap the ball',
    step3Title: '3. Score Goals!',
    step3Desc: 'Beat the goalkeeper and climb the leaderboard!',
    
    // News Page
    newsSubtitle: 'Stay updated with the latest news and features',
    news1Title: 'New Tournament Mode',
    news1Desc: 'Compete in weekly tournaments against players worldwide!',
    news2Title: 'New Teams Added',
    news2Desc: 'More teams from around the world are joining the competition.',
    news3Title: 'Multiplayer Mode',
    news3Desc: 'Challenge your friends in real-time penalty shootouts!',
    comingSoonLabel: 'Coming Soon',
    stayTuned: 'Stay Tuned!',
    stayTunedDesc: 'Follow us for updates on new features and releases.',
    
    // Country Selection
    chooseCountry: 'Choose Your Country',
    selectCountryDesc: 'Select a country to see available teams',
    back: 'Back',
    select: 'Select',
    
    // Team Selection
    chooseTeam: 'Choose Your Team',
    selectTeamDesc: 'Select a team and score goals for the global leaderboard!',
    backToCountries: 'Back to Countries',
    rank: 'Rank',
    goals: 'goals',
    playAs: 'Play as',
    globalStandings: 'Global Standings',
    goalsScored: 'goals scored',
    
    // Game
    clickToShoot: 'Click/Tap to shoot!',
    aimInstructions: 'Aim for the goal and avoid the keeper',
    selectDestination: 'Select where to shoot',
    clickBallToShoot: 'Click the ball to shoot!',
    goal: 'GOAL!',
    saved: 'SAVED!',
    out: 'OUT!',
    gameOver: 'Game Over!',
    finalScore: 'Final Score',
    goalsContributed: 'Goals contributed to',
    playAgain: 'Play Again',
    chooseDifferentTeam: 'Choose Different Team',
    goToHome: 'Go to Home',
    watchAdToPlay: 'Watch Ad to Play Again',
    backToMenu: 'Back to Menu',
    dailyLimitReached: 'Daily Limit Reached!',
    comeBackTomorrow: "You've used all your plays for today. Come back tomorrow to play again!",
    
    // Play Limit
    playsRemaining: 'Plays Remaining',
    adViewsUsed: 'Ad Views Used',
    totalToday: 'Total Today',
    playsRemainingToday: 'plays remaining today',
    
    // Ad Modal
    watchAdTitle: 'Watch a Short Ad to Continue Playing',
    watchAdDesc: "You've used your free plays. Watch a short ad to unlock 2 more plays!",
    adViewsToday: 'Ad Views Today',
    willUnlock: 'Will Unlock',
    plays: 'Plays',
    advertisement: 'Advertisement',
    pleaseWait: 'Please wait',
    seconds: 'seconds',
    readyToPlay: 'Ready to Play!',
    unlockedPlays: "You've unlocked 2 more plays",
    continuePlaying: 'Continue Playing',
    wait: 'Wait',
    exitGame: 'Exit Game',
    afterAdViews: 'After',
    morePlays: 'more plays',
    needReturnTomorrow: "you'll need to return tomorrow",
    
    // Stats
    gameStats: 'Game Statistics',
    statsDesc: 'Goals scored by teams over different periods',
    today: 'Today',
    thisMonth: 'This Month',
    thisYear: 'This Year',
    todayGoals: "Today's Goals",
    todayGoalsDesc: 'Goals scored by teams today',
    monthGoals: "This Month's Goals",
    monthGoalsDesc: 'Goals scored in',
    yearGoals: "This Year's Goals",
    yearGoalsDesc: 'Goals scored in',
    noGoalsToday: 'No goals scored today yet. Be the first!',
    noGoalsMonth: 'No goals scored this month yet.',
    noGoalsYear: 'No goals scored this year yet.',
    teamsToday: 'Teams Today',
    teamsThisMonth: 'Teams This Month',
    teamsThisYear: 'Teams This Year',
    games: 'games',
    avg: 'Avg',
    best: 'Best',
    
    // Share
    share: 'Share',
    shareOn: 'Share on',
    shareToPlay: 'Share to Play',
    shareReward: 'Share and get 2 more plays!',
    thankYouSharing: 'Thanks for sharing!',
    moreOptions: 'More Options',
    cancel: 'Cancel',
    shareLeaderboard: 'Check out the Mini Cup leaderboard!',
    shareScore: 'I scored {score} goals playing for {team} in Mini Cup!',
    helpYourTeam: '📣 Rally Your Fans!',
    helpYourTeamDesc: 'Share the leaderboard and invite friends to help your favorite team climb to the top!',
    spreadTheWord: 'Spread the Word!',
  },
  es: {
    // Landing Page
    miniCup: 'Mini Copa',
    clubWorldCup: '¿Quién es el más grande?',
    tagline: 'Ayuda a tu equipo a ganar',
    startPlaying: 'Comenzar a Jugar',
    stats: 'Estadísticas',
    comingSoon: 'Próximamente',
    adminPanel: 'Panel Admin',
    teamsCompeting: 'Equipos Compitiendo',
    totalGoals: 'Goles Totales Marcados',
    playersWorldwide: 'Jugadores en el Mundo',
    howToPlay: 'Cómo Jugar',
    step1Title: '1. Elige tu Equipo',
    step1Desc: 'Selecciona tu país y luego elige tu equipo favorito',
    step2Title: '2. Apunta y Dispara',
    step2Desc: 'Elige dónde disparar dentro del arco y toca la pelota',
    step3Title: '3. ¡Marca Goles!',
    step3Desc: '¡Vence al portero y escala en la tabla de posiciones!',
    
    // News Page
    newsSubtitle: 'Mantente actualizado con las últimas novedades',
    news1Title: 'Nuevo Modo Torneo',
    news1Desc: '¡Compite en torneos semanales contra jugadores de todo el mundo!',
    news2Title: 'Nuevos Equipos Añadidos',
    news2Desc: 'Más equipos de todo el mundo se unen a la competencia.',
    news3Title: 'Modo Multijugador',
    news3Desc: '¡Desafía a tus amigos en penales en tiempo real!',
    comingSoonLabel: 'Próximamente',
    stayTuned: '¡Mantente Atento!',
    stayTunedDesc: 'Síguenos para actualizaciones sobre nuevas funciones.',
    
    // Country Selection
    chooseCountry: 'Elige Tu País',
    selectCountryDesc: 'Selecciona un país para ver los equipos disponibles',
    back: 'Atrás',
    select: 'Seleccionar',
    
    // Team Selection
    chooseTeam: 'Elige Tu Equipo',
    selectTeamDesc: '¡Selecciona un equipo y marca goles para la tabla global!',
    backToCountries: 'Volver a Países',
    rank: 'Puesto',
    goals: 'goles',
    playAs: 'Jugar como',
    globalStandings: 'Clasificación Global',
    goalsScored: 'goles marcados',
    
    // Game
    clickToShoot: '¡Haz clic para disparar!',
    aimInstructions: 'Apunta al gol y evita al portero',
    selectDestination: 'Selecciona dónde disparar',
    clickBallToShoot: '¡Haz clic en la pelota para disparar!',
    goal: '¡GOL!',
    saved: '¡ATAJADO!',
    out: '¡FUERA!',
    gameOver: '¡Juego Terminado!',
    finalScore: 'Puntuación Final',
    goalsContributed: 'Goles contribuidos a',
    playAgain: 'Jugar de Nuevo',
    chooseDifferentTeam: 'Elegir Otro Equipo',
    goToHome: 'Ir al Inicio',
    watchAdToPlay: 'Ver Anuncio para Jugar',
    backToMenu: 'Volver al Menú',
    dailyLimitReached: '¡Límite Diario Alcanzado!',
    comeBackTomorrow: 'Has usado todas tus jugadas de hoy. ¡Vuelve mañana para jugar de nuevo!',
    
    // Play Limit
    playsRemaining: 'Jugadas Restantes',
    adViewsUsed: 'Anuncios Vistos',
    totalToday: 'Total Hoy',
    playsRemainingToday: 'jugadas restantes hoy',
    
    // Ad Modal
    watchAdTitle: 'Mira un Anuncio Corto para Continuar Jugando',
    watchAdDesc: 'Has usado tus jugadas gratis. ¡Mira un anuncio corto para desbloquear 2 jugadas más!',
    adViewsToday: 'Anuncios Hoy',
    willUnlock: 'Desbloqueará',
    plays: 'Jugadas',
    advertisement: 'Publicidad',
    pleaseWait: 'Por favor espera',
    seconds: 'segundos',
    readyToPlay: '¡Listo para Jugar!',
    unlockedPlays: 'Has desbloqueado 2 jugadas más',
    continuePlaying: 'Continuar Jugando',
    wait: 'Espera',
    exitGame: 'Salir del Juego',
    afterAdViews: 'Después de',
    morePlays: 'jugadas más',
    needReturnTomorrow: 'deberás volver mañana',
    
    // Stats
    gameStats: 'Estadísticas del Juego',
    statsDesc: 'Goles marcados por equipos en diferentes períodos',
    today: 'Hoy',
    thisMonth: 'Este Mes',
    thisYear: 'Este Año',
    todayGoals: 'Goles de Hoy',
    todayGoalsDesc: 'Goles marcados por equipos hoy',
    monthGoals: 'Goles de Este Mes',
    monthGoalsDesc: 'Goles marcados en',
    yearGoals: 'Goles de Este Año',
    yearGoalsDesc: 'Goles marcados en',
    noGoalsToday: '¡No se han marcado goles hoy! ¡Sé el primero!',
    noGoalsMonth: 'No se han marcado goles este mes.',
    noGoalsYear: 'No se han marcado goles este año.',
    teamsToday: 'Equipos Hoy',
    teamsThisMonth: 'Equipos Este Mes',
    teamsThisYear: 'Equipos Este Año',
    games: 'partidos',
    avg: 'Prom',
    best: 'Mejor',
    
    // Share
    share: 'Compartir',
    shareOn: 'Compartir en',
    shareToPlay: 'Compartir para Jugar',
    shareReward: '¡Comparte y obtén 2 jugadas más!',
    thankYouSharing: '¡Gracias por compartir!',
    moreOptions: 'Más Opciones',
    cancel: 'Cancelar',
    shareLeaderboard: '¡Mira la tabla de posiciones de Mini Copa!',
    shareScore: '¡Marqué {score} goles jugando para {team} en Mini Copa!',
    helpYourTeam: '📣 ¡Convoca a tus Fans!',
    helpYourTeamDesc: '¡Comparte la tabla y invita a tus amigos para ayudar a tu equipo favorito a llegar a la cima!',
    spreadTheWord: '¡Correr la Voz!',
  },
  pt: {
    // Landing Page
    miniCup: 'Mini Copa',
    clubWorldCup: 'Quem é o maior?',
    tagline: 'Ajude seu time a vencer',
    startPlaying: 'Começar a Jogar',
    stats: 'Estatísticas',
    comingSoon: 'Em Breve',
    adminPanel: 'Painel Admin',
    teamsCompeting: 'Equipes Competindo',
    totalGoals: 'Total de Gols Marcados',
    playersWorldwide: 'Jogadores no Mundo',
    howToPlay: 'Como Jogar',
    step1Title: '1. Escolha seu Time',
    step1Desc: 'Selecione seu país e depois escolha seu time favorito',
    step2Title: '2. Mire e Chute',
    step2Desc: 'Escolha onde chutar dentro do gol e toque na bola',
    step3Title: '3. Marque Gols!',
    step3Desc: 'Vença o goleiro e suba no ranking!',
    
    // News Page
    newsSubtitle: 'Fique atualizado com as últimas novidades',
    news1Title: 'Novo Modo Torneio',
    news1Desc: 'Compita em torneios semanais contra jogadores do mundo todo!',
    news2Title: 'Novos Times Adicionados',
    news2Desc: 'Mais times de todo o mundo estão entrando na competição.',
    news3Title: 'Modo Multiplayer',
    news3Desc: 'Desafie seus amigos em pênaltis em tempo real!',
    comingSoonLabel: 'Em Breve',
    stayTuned: 'Fique Ligado!',
    stayTunedDesc: 'Siga-nos para atualizações sobre novos recursos.',
    
    // Country Selection
    chooseCountry: 'Escolha Seu País',
    selectCountryDesc: 'Selecione um país para ver os times disponíveis',
    back: 'Voltar',
    select: 'Selecionar',
    
    // Team Selection
    chooseTeam: 'Escolha Seu Time',
    selectTeamDesc: 'Selecione um time e marque gols para o ranking global!',
    backToCountries: 'Voltar aos Países',
    rank: 'Posição',
    goals: 'gols',
    playAs: 'Jogar como',
    globalStandings: 'Classificação Global',
    goalsScored: 'gols marcados',
    
    // Game
    clickToShoot: 'Clique para chutar!',
    aimInstructions: 'Mire no gol e evite o goleiro',
    selectDestination: 'Selecione onde chutar',
    clickBallToShoot: 'Clique na bola para chutar!',
    goal: 'GOL!',
    saved: 'DEFENDEU!',
    out: 'FORA!',
    gameOver: 'Fim de Jogo!',
    finalScore: 'Pontuação Final',
    goalsContributed: 'Gols contribuídos para',
    playAgain: 'Jogar Novamente',
    chooseDifferentTeam: 'Escolher Outro Time',
    goToHome: 'Ir para Início',
    watchAdToPlay: 'Assistir Anúncio para Jogar',
    backToMenu: 'Voltar ao Menu',
    dailyLimitReached: 'Limite Diário Alcançado!',
    comeBackTomorrow: 'Você usou todas as suas jogadas hoje. Volte amanhã para jogar novamente!',
    
    // Play Limit
    playsRemaining: 'Jogadas Restantes',
    adViewsUsed: 'Anúncios Vistos',
    totalToday: 'Total Hoje',
    playsRemainingToday: 'jogadas restantes hoje',
    
    // Ad Modal
    watchAdTitle: 'Assista um Anúncio Curto para Continuar Jogando',
    watchAdDesc: 'Você usou suas jogadas grátis. Assista um anúncio curto para desbloquear 2 jogadas a mais!',
    adViewsToday: 'Anúncios Hoje',
    willUnlock: 'Desbloqueará',
    plays: 'Jogadas',
    advertisement: 'Publicidade',
    pleaseWait: 'Por favor aguarde',
    seconds: 'segundos',
    readyToPlay: 'Pronto para Jogar!',
    unlockedPlays: 'Você desbloqueou 2 jogadas a mais',
    continuePlaying: 'Continuar Jogando',
    wait: 'Aguarde',
    exitGame: 'Sair do Jogo',
    afterAdViews: 'Após',
    morePlays: 'jogadas a mais',
    needReturnTomorrow: 'você precisará voltar amanhã',
    
    // Stats
    gameStats: 'Estatísticas do Jogo',
    statsDesc: 'Gols marcados por times em diferentes períodos',
    today: 'Hoje',
    thisMonth: 'Este Mês',
    thisYear: 'Este Ano',
    todayGoals: 'Gols de Hoje',
    todayGoalsDesc: 'Gols marcados por times hoje',
    monthGoals: 'Gols Deste Mês',
    monthGoalsDesc: 'Gols marcados em',
    yearGoals: 'Gols Deste Ano',
    yearGoalsDesc: 'Gols marcados em',
    noGoalsToday: 'Nenhum gol marcado hoje ainda. Seja o primeiro!',
    noGoalsMonth: 'Nenhum gol marcado este mês ainda.',
    noGoalsYear: 'Nenhum gol marcado este ano ainda.',
    teamsToday: 'Times Hoje',
    teamsThisMonth: 'Times Este Mês',
    teamsThisYear: 'Times Este Ano',
    games: 'jogos',
    avg: 'Méd',
    best: 'Melhor',
    
    // Share
    share: 'Compartilhar',
    shareOn: 'Compartilhar em',
    shareToPlay: 'Compartilhar para Jogar',
    shareReward: 'Compartilhe e ganhe 2 jogadas a mais!',
    thankYouSharing: 'Obrigado por compartilhar!',
    moreOptions: 'Mais Opções',
    cancel: 'Cancelar',
    shareLeaderboard: 'Confira o ranking da Mini Copa!',
    shareScore: 'Marquei {score} gols jogando pelo {team} na Mini Copa!',
    helpYourTeam: '📣 Convoque seus Torcedores!',
    helpYourTeamDesc: 'Compartilhe o ranking e convide amigos para ajudar seu time favorito a chegar ao topo!',
    spreadTheWord: 'Espalhe a Notícia!',
  },
  fr: {
    // Landing Page
    miniCup: 'Mini Coupe',
    clubWorldCup: 'Qui est le plus grand?',
    tagline: 'Aidez votre équipe à gagner',
    startPlaying: 'Commencer à Jouer',
    stats: 'Statistiques',
    comingSoon: 'Bientôt',
    adminPanel: 'Panneau Admin',
    teamsCompeting: 'Équipes en Compétition',
    totalGoals: 'Total de Buts Marqués',
    playersWorldwide: 'Joueurs dans le Monde',
    howToPlay: 'Comment Jouer',
    step1Title: '1. Choisissez votre Équipe',
    step1Desc: 'Sélectionnez votre pays, puis choisissez votre équipe préférée',
    step2Title: '2. Visez et Tirez',
    step2Desc: 'Choisissez où tirer dans le but, puis touchez le ballon',
    step3Title: '3. Marquez des Buts!',
    step3Desc: 'Battez le gardien et grimpez dans le classement!',
    
    // News Page
    newsSubtitle: 'Restez informé des dernières nouvelles',
    news1Title: 'Nouveau Mode Tournoi',
    news1Desc: 'Participez à des tournois hebdomadaires contre des joueurs du monde entier!',
    news2Title: 'Nouvelles Équipes Ajoutées',
    news2Desc: 'Plus d\'équipes du monde entier rejoignent la compétition.',
    news3Title: 'Mode Multijoueur',
    news3Desc: 'Défiez vos amis en tirs au but en temps réel!',
    comingSoonLabel: 'Bientôt',
    stayTuned: 'Restez à l\'écoute!',
    stayTunedDesc: 'Suivez-nous pour les mises à jour sur les nouvelles fonctionnalités.',
    
    // Country Selection
    chooseCountry: 'Choisissez Votre Pays',
    selectCountryDesc: 'Sélectionnez un pays pour voir les équipes disponibles',
    back: 'Retour',
    select: 'Sélectionner',
    
    // Team Selection
    chooseTeam: 'Choisissez Votre Équipe',
    selectTeamDesc: 'Sélectionnez une équipe et marquez des buts pour le classement mondial!',
    backToCountries: 'Retour aux Pays',
    rank: 'Rang',
    goals: 'buts',
    playAs: 'Jouer comme',
    globalStandings: 'Classement Mondial',
    goalsScored: 'buts marqués',
    
    // Game
    clickToShoot: 'Cliquez pour tirer!',
    aimInstructions: 'Visez le but et évitez le gardien',
    selectDestination: 'Sélectionnez où tirer',
    clickBallToShoot: 'Cliquez sur le ballon pour tirer!',
    goal: 'BUT!',
    saved: 'ARRÊTÉ!',
    out: 'DEHORS!',
    gameOver: 'Fin du Jeu!',
    finalScore: 'Score Final',
    goalsContributed: 'Buts contribués à',
    playAgain: 'Rejouer',
    chooseDifferentTeam: 'Choisir une Autre Équipe',
    goToHome: 'Aller à l\'Accueil',
    watchAdToPlay: 'Regarder une Pub pour Jouer',
    backToMenu: 'Retour au Menu',
    dailyLimitReached: 'Limite Quotidienne Atteinte!',
    comeBackTomorrow: 'Vous avez utilisé toutes vos parties aujourd\'hui. Revenez demain pour rejouer!',
    
    // Play Limit
    playsRemaining: 'Parties Restantes',
    adViewsUsed: 'Pubs Vues',
    totalToday: 'Total Aujourd\'hui',
    playsRemainingToday: 'parties restantes aujourd\'hui',
    
    // Ad Modal
    watchAdTitle: 'Regardez une Courte Pub pour Continuer à Jouer',
    watchAdDesc: 'Vous avez utilisé vos parties gratuites. Regardez une courte pub pour débloquer 2 parties de plus!',
    adViewsToday: 'Pubs Aujourd\'hui',
    willUnlock: 'Débloquera',
    plays: 'Parties',
    advertisement: 'Publicité',
    pleaseWait: 'Veuillez patienter',
    seconds: 'secondes',
    readyToPlay: 'Prêt à Jouer!',
    unlockedPlays: 'Vous avez débloqué 2 parties de plus',
    continuePlaying: 'Continuer à Jouer',
    wait: 'Attendez',
    exitGame: 'Quitter le Jeu',
    afterAdViews: 'Après',
    morePlays: 'parties de plus',
    needReturnTomorrow: 'vous devrez revenir demain',
    
    // Stats
    gameStats: 'Statistiques du Jeu',
    statsDesc: 'Buts marqués par les équipes sur différentes périodes',
    today: 'Aujourd\'hui',
    thisMonth: 'Ce Mois',
    thisYear: 'Cette Année',
    todayGoals: 'Buts d\'Aujourd\'hui',
    todayGoalsDesc: 'Buts marqués par les équipes aujourd\'hui',
    monthGoals: 'Buts de Ce Mois',
    monthGoalsDesc: 'Buts marqués en',
    yearGoals: 'Buts de Cette Année',
    yearGoalsDesc: 'Buts marqués en',
    noGoalsToday: 'Aucun but marqué aujourd\'hui. Soyez le premier!',
    noGoalsMonth: 'Aucun but marqué ce mois.',
    noGoalsYear: 'Aucun but marqué cette année.',
    teamsToday: 'Équipes Aujourd\'hui',
    teamsThisMonth: 'Équipes Ce Mois',
    teamsThisYear: 'Équipes Cette Année',
    games: 'matchs',
    avg: 'Moy',
    best: 'Meilleur',
    
    // Share
    share: 'Partager',
    shareOn: 'Partager sur',
    shareToPlay: 'Partager pour Jouer',
    shareReward: 'Partagez et obtenez 2 parties de plus!',
    thankYouSharing: 'Merci d\'avoir partagé!',
    moreOptions: 'Plus d\'Options',
    cancel: 'Annuler',
    shareLeaderboard: 'Consultez le classement Mini Coupe!',
    shareScore: 'J\'ai marqué {score} buts en jouant pour {team} dans Mini Coupe!',
    helpYourTeam: '📣 Ralliez vos Supporters!',
    helpYourTeamDesc: 'Partagez le classement et invitez vos amis à aider votre équipe favorite à atteindre le sommet!',
    spreadTheWord: 'Faites Passer le Mot!',
  },
  it: {
    // Landing Page
    miniCup: 'Mini Coppa',
    clubWorldCup: 'Chi è il più grande?',
    tagline: 'Aiuta la tua squadra a vincere',
    startPlaying: 'Inizia a Giocare',
    stats: 'Statistiche',
    adminPanel: 'Pannello Admin',
    teamsCompeting: 'Squadre in Competizione',
    totalGoals: 'Totale Gol Segnati',
    playersWorldwide: 'Giocatori nel Mondo',
    howToPlay: 'Come Giocare',
    step1Title: '1. Scegli la tua Squadra',
    step1Desc: 'Seleziona il tuo paese, poi scegli la tua squadra preferita',
    step2Title: '2. Mira e Tira',
    step2Desc: 'Scegli dove tirare nella porta, poi tocca la palla',
    step3Title: '3. Segna Gol!',
    step3Desc: 'Batti il portiere e scala la classifica!',
    
    // Country Selection
    chooseCountry: 'Scegli il Tuo Paese',
    selectCountryDesc: 'Seleziona un paese per vedere le squadre disponibili',
    back: 'Indietro',
    select: 'Seleziona',
    
    // Team Selection
    chooseTeam: 'Scegli la Tua Squadra',
    selectTeamDesc: 'Seleziona una squadra e segna gol per la classifica globale!',
    backToCountries: 'Torna ai Paesi',
    rank: 'Posizione',
    goals: 'gol',
    playAs: 'Gioca come',
    globalStandings: 'Classifica Globale',
    goalsScored: 'gol segnati',
    
    // Game
    clickToShoot: 'Clicca per tirare!',
    aimInstructions: 'Mira alla porta ed evita il portiere',
    selectDestination: 'Seleziona dove tirare',
    clickBallToShoot: 'Clicca sulla palla per tirare!',
    goal: 'GOL!',
    saved: 'PARATO!',
    out: 'FUORI!',
    gameOver: 'Fine Gioco!',
    finalScore: 'Punteggio Finale',
    goalsContributed: 'Gol contribuiti a',
    playAgain: 'Gioca Ancora',
    chooseDifferentTeam: 'Scegli un\'Altra Squadra',
    goToHome: 'Vai alla Home',
    watchAdToPlay: 'Guarda Annuncio per Giocare',
    backToMenu: 'Torna al Menu',
    dailyLimitReached: 'Limite Giornaliero Raggiunto!',
    comeBackTomorrow: 'Hai usato tutte le tue partite oggi. Torna domani per giocare ancora!',
    
    // Play Limit
    playsRemaining: 'Partite Rimanenti',
    adViewsUsed: 'Annunci Visti',
    totalToday: 'Totale Oggi',
    playsRemainingToday: 'partite rimanenti oggi',
    
    // Ad Modal
    watchAdTitle: 'Guarda un Breve Annuncio per Continuare a Giocare',
    watchAdDesc: 'Hai usato le tue partite gratuite. Guarda un breve annuncio per sbloccare 2 partite in più!',
    adViewsToday: 'Annunci Oggi',
    willUnlock: 'Sbloccherà',
    plays: 'Partite',
    advertisement: 'Pubblicità',
    pleaseWait: 'Attendere prego',
    seconds: 'secondi',
    readyToPlay: 'Pronto a Giocare!',
    unlockedPlays: 'Hai sbloccato 2 partite in più',
    continuePlaying: 'Continua a Giocare',
    wait: 'Aspetta',
    exitGame: 'Esci dal Gioco',
    afterAdViews: 'Dopo',
    morePlays: 'partite in più',
    needReturnTomorrow: 'dovrai tornare domani',
    
    // Stats
    gameStats: 'Statistiche del Gioco',
    statsDesc: 'Gol segnati dalle squadre in diversi periodi',
    today: 'Oggi',
    thisMonth: 'Questo Mese',
    thisYear: 'Quest\'Anno',
    todayGoals: 'Gol di Oggi',
    todayGoalsDesc: 'Gol segnati dalle squadre oggi',
    monthGoals: 'Gol di Questo Mese',
    monthGoalsDesc: 'Gol segnati in',
    yearGoals: 'Gol di Quest\'Anno',
    yearGoalsDesc: 'Gol segnati in',
    noGoalsToday: 'Nessun gol segnato oggi. Sii il primo!',
    noGoalsMonth: 'Nessun gol segnato questo mese.',
    noGoalsYear: 'Nessun gol segnato quest\'anno.',
    teamsToday: 'Squadre Oggi',
    teamsThisMonth: 'Squadre Questo Mese',
    teamsThisYear: 'Squadre Quest\'Anno',
    games: 'partite',
    avg: 'Media',
    best: 'Migliore',
    
    // Share
    share: 'Condividi',
    shareOn: 'Condividi su',
    shareToPlay: 'Condividi per Giocare',
    shareReward: 'Condividi e ottieni 2 partite in più!',
    thankYouSharing: 'Grazie per aver condiviso!',
    moreOptions: 'Altre Opzioni',
    cancel: 'Annulla',
    shareLeaderboard: 'Guarda la classifica Mini Coppa!',
    shareScore: 'Ho segnato {score} gol giocando per {team} in Mini Coppa!',
    helpYourTeam: '📣 Raduna i tuoi Tifosi!',
    helpYourTeamDesc: 'Condividi la classifica e invita gli amici ad aiutare la tua squadra preferita a raggiungere la vetta!',
    spreadTheWord: 'Diffondi la Voce!',
  },
};

const LANGUAGES = [
  { code: 'es', name: 'Español', flag: '🇪🇸' },
  { code: 'en', name: 'English', flag: '🇬🇧' },
  { code: 'pt', name: 'Português', flag: '🇧🇷' },
  { code: 'fr', name: 'Français', flag: '🇫🇷' },
  { code: 'it', name: 'Italiano', flag: '🇮🇹' },
];

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState('es'); // Spanish by default

  useEffect(() => {
    const savedLanguage = localStorage.getItem('gameLanguage');
    if (savedLanguage && translations[savedLanguage]) {
      setLanguage(savedLanguage);
    }
  }, []);

  const changeLanguage = (lang) => {
    if (translations[lang]) {
      setLanguage(lang);
      localStorage.setItem('gameLanguage', lang);
    }
  };

  const t = (key) => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, changeLanguage, t, languages: LANGUAGES }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};